basePath: /
consumes:
- application/json
definitions:
  controller.Link:
    properties:
      href:
        type: string
      method:
        type: string
    type: object
  controller.Resource:
    properties:
      data: {}
      links:
        additionalProperties:
          $ref: '#/definitions/controller.Link'
        type: object
    type: object
  domain.Gender:
    enum:
    - male
    - female
    - other
    - prefer_not_to_say
    type: string
    x-enum-varnames:
    - Male
    - Female
    - Other
    - PreferNotToSay
  middleware.ErrorResponse:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  port.RegisterUserInput:
    properties:
      date_of_birth:
        type: string
      email:
        type: string
      first_name:
        minLength: 2
        type: string
      gender:
        allOf:
        - $ref: '#/definitions/domain.Gender'
        enum:
        - male
        - female
        - prefer_not_to_say
        - other
      last_name:
        minLength: 2
        type: string
      password:
        maxLength: 12
        minLength: 8
        type: string
      phone:
        type: string
    required:
    - date_of_birth
    - email
    - first_name
    - last_name
    - password
    - phone
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API documentation for the Cinemax application.
  title: Cinemax API
  version: "1.0"
paths:
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Register a new user with the provided information.
      parameters:
      - description: User registration data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/port.RegisterUserInput'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully
          schema:
            $ref: '#/definitions/controller.Resource'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/middleware.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/middleware.ErrorResponse'
      summary: Register a user
      tags:
      - Auth
produces:
- application/json
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
